### ISSUE TITLE
i get an error while pinging a website. am i doing something wrong here?

### ISSUE THREAD

**Issue by ghostcode1** [Isloka/tor-pinger#1]
(node:9359) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'statusCode' of undefined

    at Object.callback (/root/tor-pinger/index.js:25:41)

    at Request._callback (/root/node_modules/tor-request/index.js:198:35)

    at self.callback (/root/node_modules/request/request.js:185:22)

    at Request.emit (events.js:376:20)

    at Request.onRequestError (/root/node_modules/request/request.js:877:8)

    at ClientRequest.emit (events.js:376:20)

    at onerror (/root/node_modules/agent-base/index.js:101:9)

    at callbackError (/root/node_modules/agent-base/index.js:123:5)

    at processTicksAndRejections (internal/process/task_queues.js:95:5)

(Use `node --trace-warnings ...` to show where the warning was created)

(node:9359) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:9359) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Isloka** [comment]
Sorry for the delay, I was traveling, the issue seems to occur while fetching the status code of the request, can you give me more information? For example, the url, the source code and the NodeJS version? Thank you!
